<?php
/**
 * Adnotacje
 *
 * PHP version 5
 *
 * @category Class
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * Adnotacje Class Doc Comment
 *
 * @category Class
 * @description Inne adnotacje na fakturze
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Adnotacje implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Adnotacje';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'p_16' => '\NIP24\Model\TWybor12',
'p_17' => '\NIP24\Model\TWybor12',
'p_18' => '\NIP24\Model\TWybor12',
'p_18_a' => '\NIP24\Model\TWybor12',
'zwolnienie' => '\NIP24\Model\Zwolnienie',
'nowe_srodki_transportu' => '\NIP24\Model\NoweSrodkiTransportu',
'p_23' => '\NIP24\Model\TWybor12',
'p_marzy' => '\NIP24\Model\PMarzy'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'p_16' => null,
'p_17' => null,
'p_18' => null,
'p_18_a' => null,
'zwolnienie' => null,
'nowe_srodki_transportu' => null,
'p_23' => null,
'p_marzy' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'p_16' => 'P_16',
'p_17' => 'P_17',
'p_18' => 'P_18',
'p_18_a' => 'P_18A',
'zwolnienie' => 'Zwolnienie',
'nowe_srodki_transportu' => 'NoweSrodkiTransportu',
'p_23' => 'P_23',
'p_marzy' => 'PMarzy'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'p_16' => 'setP16',
'p_17' => 'setP17',
'p_18' => 'setP18',
'p_18_a' => 'setP18A',
'zwolnienie' => 'setZwolnienie',
'nowe_srodki_transportu' => 'setNoweSrodkiTransportu',
'p_23' => 'setP23',
'p_marzy' => 'setPMarzy'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'p_16' => 'getP16',
'p_17' => 'getP17',
'p_18' => 'getP18',
'p_18_a' => 'getP18A',
'zwolnienie' => 'getZwolnienie',
'nowe_srodki_transportu' => 'getNoweSrodkiTransportu',
'p_23' => 'getP23',
'p_marzy' => 'getPMarzy'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['p_16'] = isset($data['p_16']) ? $data['p_16'] : null;
        $this->container['p_17'] = isset($data['p_17']) ? $data['p_17'] : null;
        $this->container['p_18'] = isset($data['p_18']) ? $data['p_18'] : null;
        $this->container['p_18_a'] = isset($data['p_18_a']) ? $data['p_18_a'] : null;
        $this->container['zwolnienie'] = isset($data['zwolnienie']) ? $data['zwolnienie'] : null;
        $this->container['nowe_srodki_transportu'] = isset($data['nowe_srodki_transportu']) ? $data['nowe_srodki_transportu'] : null;
        $this->container['p_23'] = isset($data['p_23']) ? $data['p_23'] : null;
        $this->container['p_marzy'] = isset($data['p_marzy']) ? $data['p_marzy'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['p_16'] === null) {
            $invalidProperties[] = "'p_16' can't be null";
        }
        if ($this->container['p_17'] === null) {
            $invalidProperties[] = "'p_17' can't be null";
        }
        if ($this->container['p_18'] === null) {
            $invalidProperties[] = "'p_18' can't be null";
        }
        if ($this->container['p_18_a'] === null) {
            $invalidProperties[] = "'p_18_a' can't be null";
        }
        if ($this->container['zwolnienie'] === null) {
            $invalidProperties[] = "'zwolnienie' can't be null";
        }
        if ($this->container['nowe_srodki_transportu'] === null) {
            $invalidProperties[] = "'nowe_srodki_transportu' can't be null";
        }
        if ($this->container['p_23'] === null) {
            $invalidProperties[] = "'p_23' can't be null";
        }
        if ($this->container['p_marzy'] === null) {
            $invalidProperties[] = "'p_marzy' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets p_16
     *
     * @return \NIP24\Model\TWybor12
     */
    public function getP16()
    {
        return $this->container['p_16'];
    }

    /**
     * Sets p_16
     *
     * @param \NIP24\Model\TWybor12 $p_16 p_16
     *
     * @return $this
     */
    public function setP16($p_16)
    {
        $this->container['p_16'] = $p_16;

        return $this;
    }

    /**
     * Gets p_17
     *
     * @return \NIP24\Model\TWybor12
     */
    public function getP17()
    {
        return $this->container['p_17'];
    }

    /**
     * Sets p_17
     *
     * @param \NIP24\Model\TWybor12 $p_17 p_17
     *
     * @return $this
     */
    public function setP17($p_17)
    {
        $this->container['p_17'] = $p_17;

        return $this;
    }

    /**
     * Gets p_18
     *
     * @return \NIP24\Model\TWybor12
     */
    public function getP18()
    {
        return $this->container['p_18'];
    }

    /**
     * Sets p_18
     *
     * @param \NIP24\Model\TWybor12 $p_18 p_18
     *
     * @return $this
     */
    public function setP18($p_18)
    {
        $this->container['p_18'] = $p_18;

        return $this;
    }

    /**
     * Gets p_18_a
     *
     * @return \NIP24\Model\TWybor12
     */
    public function getP18A()
    {
        return $this->container['p_18_a'];
    }

    /**
     * Sets p_18_a
     *
     * @param \NIP24\Model\TWybor12 $p_18_a p_18_a
     *
     * @return $this
     */
    public function setP18A($p_18_a)
    {
        $this->container['p_18_a'] = $p_18_a;

        return $this;
    }

    /**
     * Gets zwolnienie
     *
     * @return \NIP24\Model\Zwolnienie
     */
    public function getZwolnienie()
    {
        return $this->container['zwolnienie'];
    }

    /**
     * Sets zwolnienie
     *
     * @param \NIP24\Model\Zwolnienie $zwolnienie zwolnienie
     *
     * @return $this
     */
    public function setZwolnienie($zwolnienie)
    {
        $this->container['zwolnienie'] = $zwolnienie;

        return $this;
    }

    /**
     * Gets nowe_srodki_transportu
     *
     * @return \NIP24\Model\NoweSrodkiTransportu
     */
    public function getNoweSrodkiTransportu()
    {
        return $this->container['nowe_srodki_transportu'];
    }

    /**
     * Sets nowe_srodki_transportu
     *
     * @param \NIP24\Model\NoweSrodkiTransportu $nowe_srodki_transportu nowe_srodki_transportu
     *
     * @return $this
     */
    public function setNoweSrodkiTransportu($nowe_srodki_transportu)
    {
        $this->container['nowe_srodki_transportu'] = $nowe_srodki_transportu;

        return $this;
    }

    /**
     * Gets p_23
     *
     * @return \NIP24\Model\TWybor12
     */
    public function getP23()
    {
        return $this->container['p_23'];
    }

    /**
     * Sets p_23
     *
     * @param \NIP24\Model\TWybor12 $p_23 p_23
     *
     * @return $this
     */
    public function setP23($p_23)
    {
        $this->container['p_23'] = $p_23;

        return $this;
    }

    /**
     * Gets p_marzy
     *
     * @return \NIP24\Model\PMarzy
     */
    public function getPMarzy()
    {
        return $this->container['p_marzy'];
    }

    /**
     * Sets p_marzy
     *
     * @param \NIP24\Model\PMarzy $p_marzy p_marzy
     *
     * @return $this
     */
    public function setPMarzy($p_marzy)
    {
        $this->container['p_marzy'] = $p_marzy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
