<?php
/**
 * Dane
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: kontakt@nip24.pl
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * Dane Class Doc Comment
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Dane implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Dane';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'dzial1' => '\NIP24\Model\Dzial1',
        'dzial2' => '\NIP24\Model\Dzial2',
        'dzial3' => '\NIP24\Model\Dzial3',
        'dzial4' => '\NIP24\Model\Dzial4',
        'dzial5' => '\NIP24\Model\Dzial5',
        'dzial6' => '\NIP24\Model\Dzial6'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'dzial1' => null,
        'dzial2' => null,
        'dzial3' => null,
        'dzial4' => null,
        'dzial5' => null,
        'dzial6' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'dzial1' => false,
        'dzial2' => false,
        'dzial3' => false,
        'dzial4' => false,
        'dzial5' => false,
        'dzial6' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dzial1' => 'dzial1',
        'dzial2' => 'dzial2',
        'dzial3' => 'dzial3',
        'dzial4' => 'dzial4',
        'dzial5' => 'dzial5',
        'dzial6' => 'dzial6'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dzial1' => 'setDzial1',
        'dzial2' => 'setDzial2',
        'dzial3' => 'setDzial3',
        'dzial4' => 'setDzial4',
        'dzial5' => 'setDzial5',
        'dzial6' => 'setDzial6'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dzial1' => 'getDzial1',
        'dzial2' => 'getDzial2',
        'dzial3' => 'getDzial3',
        'dzial4' => 'getDzial4',
        'dzial5' => 'getDzial5',
        'dzial6' => 'getDzial6'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('dzial1', $data ?? [], null);
        $this->setIfExists('dzial2', $data ?? [], null);
        $this->setIfExists('dzial3', $data ?? [], null);
        $this->setIfExists('dzial4', $data ?? [], null);
        $this->setIfExists('dzial5', $data ?? [], null);
        $this->setIfExists('dzial6', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dzial1
     *
     * @return \NIP24\Model\Dzial1|null
     */
    public function getDzial1()
    {
        return $this->container['dzial1'];
    }

    /**
     * Sets dzial1
     *
     * @param \NIP24\Model\Dzial1|null $dzial1 dzial1
     *
     * @return self
     */
    public function setDzial1($dzial1)
    {
        if (is_null($dzial1)) {
            throw new \InvalidArgumentException('non-nullable dzial1 cannot be null');
        }
        $this->container['dzial1'] = $dzial1;

        return $this;
    }

    /**
     * Gets dzial2
     *
     * @return \NIP24\Model\Dzial2|null
     */
    public function getDzial2()
    {
        return $this->container['dzial2'];
    }

    /**
     * Sets dzial2
     *
     * @param \NIP24\Model\Dzial2|null $dzial2 dzial2
     *
     * @return self
     */
    public function setDzial2($dzial2)
    {
        if (is_null($dzial2)) {
            throw new \InvalidArgumentException('non-nullable dzial2 cannot be null');
        }
        $this->container['dzial2'] = $dzial2;

        return $this;
    }

    /**
     * Gets dzial3
     *
     * @return \NIP24\Model\Dzial3|null
     */
    public function getDzial3()
    {
        return $this->container['dzial3'];
    }

    /**
     * Sets dzial3
     *
     * @param \NIP24\Model\Dzial3|null $dzial3 dzial3
     *
     * @return self
     */
    public function setDzial3($dzial3)
    {
        if (is_null($dzial3)) {
            throw new \InvalidArgumentException('non-nullable dzial3 cannot be null');
        }
        $this->container['dzial3'] = $dzial3;

        return $this;
    }

    /**
     * Gets dzial4
     *
     * @return \NIP24\Model\Dzial4|null
     */
    public function getDzial4()
    {
        return $this->container['dzial4'];
    }

    /**
     * Sets dzial4
     *
     * @param \NIP24\Model\Dzial4|null $dzial4 dzial4
     *
     * @return self
     */
    public function setDzial4($dzial4)
    {
        if (is_null($dzial4)) {
            throw new \InvalidArgumentException('non-nullable dzial4 cannot be null');
        }
        $this->container['dzial4'] = $dzial4;

        return $this;
    }

    /**
     * Gets dzial5
     *
     * @return \NIP24\Model\Dzial5|null
     */
    public function getDzial5()
    {
        return $this->container['dzial5'];
    }

    /**
     * Sets dzial5
     *
     * @param \NIP24\Model\Dzial5|null $dzial5 dzial5
     *
     * @return self
     */
    public function setDzial5($dzial5)
    {
        if (is_null($dzial5)) {
            throw new \InvalidArgumentException('non-nullable dzial5 cannot be null');
        }
        $this->container['dzial5'] = $dzial5;

        return $this;
    }

    /**
     * Gets dzial6
     *
     * @return \NIP24\Model\Dzial6|null
     */
    public function getDzial6()
    {
        return $this->container['dzial6'];
    }

    /**
     * Sets dzial6
     *
     * @param \NIP24\Model\Dzial6|null $dzial6 dzial6
     *
     * @return self
     */
    public function setDzial6($dzial6)
    {
        if (is_null($dzial6)) {
            throw new \InvalidArgumentException('non-nullable dzial6 cannot be null');
        }
        $this->container['dzial6'] = $dzial6;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


