<?php
/**
 * Dzial1
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: kontakt@nip24.pl
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * Dzial1 Class Doc Comment
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Dzial1 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Dzial1';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'organ_sprawujacy_nadzor' => '\NIP24\Model\OrganSprawujacyNadzor',
        'dane_podmiotu' => '\NIP24\Model\DanePodmiotu',
        'siedziba_i_adres' => '\NIP24\Model\SiedzibaIAdres',
        'jednostki_terenowe_oddzialy' => '\NIP24\Model\JednostkiTerenoweOddzialy[]',
        'umowa_statut' => '\NIP24\Model\UmowaStatut',
        'pozostale_informacje' => '\NIP24\Model\PozostaleInformacje',
        'wspolnicy_spzoo' => '\NIP24\Model\WspolnicySpzoo[]',
        'jedyny_akcjonariusz' => '\NIP24\Model\JedynyAkcjonariusz[]',
        'sposob_powstania_podmiotu' => '\NIP24\Model\SposobPowstaniaPodmiotu',
        'kapital' => '\NIP24\Model\Kapital',
        'emisje_akcji' => '\NIP24\Model\EmisjeAkcji[]',
        'wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych' => '\NIP24\Model\WzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych',
        'wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych' => '\NIP24\Model\WzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'organ_sprawujacy_nadzor' => null,
        'dane_podmiotu' => null,
        'siedziba_i_adres' => null,
        'jednostki_terenowe_oddzialy' => null,
        'umowa_statut' => null,
        'pozostale_informacje' => null,
        'wspolnicy_spzoo' => null,
        'jedyny_akcjonariusz' => null,
        'sposob_powstania_podmiotu' => null,
        'kapital' => null,
        'emisje_akcji' => null,
        'wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych' => null,
        'wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'organ_sprawujacy_nadzor' => false,
        'dane_podmiotu' => false,
        'siedziba_i_adres' => false,
        'jednostki_terenowe_oddzialy' => false,
        'umowa_statut' => false,
        'pozostale_informacje' => false,
        'wspolnicy_spzoo' => false,
        'jedyny_akcjonariusz' => false,
        'sposob_powstania_podmiotu' => false,
        'kapital' => false,
        'emisje_akcji' => false,
        'wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych' => false,
        'wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'organ_sprawujacy_nadzor' => 'organSprawujacyNadzor',
        'dane_podmiotu' => 'danePodmiotu',
        'siedziba_i_adres' => 'siedzibaIAdres',
        'jednostki_terenowe_oddzialy' => 'jednostkiTerenoweOddzialy',
        'umowa_statut' => 'umowaStatut',
        'pozostale_informacje' => 'pozostaleInformacje',
        'wspolnicy_spzoo' => 'wspolnicySpzoo',
        'jedyny_akcjonariusz' => 'jedynyAkcjonariusz',
        'sposob_powstania_podmiotu' => 'sposobPowstaniaPodmiotu',
        'kapital' => 'kapital',
        'emisje_akcji' => 'emisjeAkcji',
        'wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych' => 'wzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych',
        'wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych' => 'wzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'organ_sprawujacy_nadzor' => 'setOrganSprawujacyNadzor',
        'dane_podmiotu' => 'setDanePodmiotu',
        'siedziba_i_adres' => 'setSiedzibaIAdres',
        'jednostki_terenowe_oddzialy' => 'setJednostkiTerenoweOddzialy',
        'umowa_statut' => 'setUmowaStatut',
        'pozostale_informacje' => 'setPozostaleInformacje',
        'wspolnicy_spzoo' => 'setWspolnicySpzoo',
        'jedyny_akcjonariusz' => 'setJedynyAkcjonariusz',
        'sposob_powstania_podmiotu' => 'setSposobPowstaniaPodmiotu',
        'kapital' => 'setKapital',
        'emisje_akcji' => 'setEmisjeAkcji',
        'wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych' => 'setWzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych',
        'wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych' => 'setWzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'organ_sprawujacy_nadzor' => 'getOrganSprawujacyNadzor',
        'dane_podmiotu' => 'getDanePodmiotu',
        'siedziba_i_adres' => 'getSiedzibaIAdres',
        'jednostki_terenowe_oddzialy' => 'getJednostkiTerenoweOddzialy',
        'umowa_statut' => 'getUmowaStatut',
        'pozostale_informacje' => 'getPozostaleInformacje',
        'wspolnicy_spzoo' => 'getWspolnicySpzoo',
        'jedyny_akcjonariusz' => 'getJedynyAkcjonariusz',
        'sposob_powstania_podmiotu' => 'getSposobPowstaniaPodmiotu',
        'kapital' => 'getKapital',
        'emisje_akcji' => 'getEmisjeAkcji',
        'wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych' => 'getWzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych',
        'wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych' => 'getWzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('organ_sprawujacy_nadzor', $data ?? [], null);
        $this->setIfExists('dane_podmiotu', $data ?? [], null);
        $this->setIfExists('siedziba_i_adres', $data ?? [], null);
        $this->setIfExists('jednostki_terenowe_oddzialy', $data ?? [], null);
        $this->setIfExists('umowa_statut', $data ?? [], null);
        $this->setIfExists('pozostale_informacje', $data ?? [], null);
        $this->setIfExists('wspolnicy_spzoo', $data ?? [], null);
        $this->setIfExists('jedyny_akcjonariusz', $data ?? [], null);
        $this->setIfExists('sposob_powstania_podmiotu', $data ?? [], null);
        $this->setIfExists('kapital', $data ?? [], null);
        $this->setIfExists('emisje_akcji', $data ?? [], null);
        $this->setIfExists('wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych', $data ?? [], null);
        $this->setIfExists('wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets organ_sprawujacy_nadzor
     *
     * @return \NIP24\Model\OrganSprawujacyNadzor|null
     */
    public function getOrganSprawujacyNadzor()
    {
        return $this->container['organ_sprawujacy_nadzor'];
    }

    /**
     * Sets organ_sprawujacy_nadzor
     *
     * @param \NIP24\Model\OrganSprawujacyNadzor|null $organ_sprawujacy_nadzor organ_sprawujacy_nadzor
     *
     * @return self
     */
    public function setOrganSprawujacyNadzor($organ_sprawujacy_nadzor)
    {
        if (is_null($organ_sprawujacy_nadzor)) {
            throw new \InvalidArgumentException('non-nullable organ_sprawujacy_nadzor cannot be null');
        }
        $this->container['organ_sprawujacy_nadzor'] = $organ_sprawujacy_nadzor;

        return $this;
    }

    /**
     * Gets dane_podmiotu
     *
     * @return \NIP24\Model\DanePodmiotu|null
     */
    public function getDanePodmiotu()
    {
        return $this->container['dane_podmiotu'];
    }

    /**
     * Sets dane_podmiotu
     *
     * @param \NIP24\Model\DanePodmiotu|null $dane_podmiotu dane_podmiotu
     *
     * @return self
     */
    public function setDanePodmiotu($dane_podmiotu)
    {
        if (is_null($dane_podmiotu)) {
            throw new \InvalidArgumentException('non-nullable dane_podmiotu cannot be null');
        }
        $this->container['dane_podmiotu'] = $dane_podmiotu;

        return $this;
    }

    /**
     * Gets siedziba_i_adres
     *
     * @return \NIP24\Model\SiedzibaIAdres|null
     */
    public function getSiedzibaIAdres()
    {
        return $this->container['siedziba_i_adres'];
    }

    /**
     * Sets siedziba_i_adres
     *
     * @param \NIP24\Model\SiedzibaIAdres|null $siedziba_i_adres siedziba_i_adres
     *
     * @return self
     */
    public function setSiedzibaIAdres($siedziba_i_adres)
    {
        if (is_null($siedziba_i_adres)) {
            throw new \InvalidArgumentException('non-nullable siedziba_i_adres cannot be null');
        }
        $this->container['siedziba_i_adres'] = $siedziba_i_adres;

        return $this;
    }

    /**
     * Gets jednostki_terenowe_oddzialy
     *
     * @return \NIP24\Model\JednostkiTerenoweOddzialy[]|null
     */
    public function getJednostkiTerenoweOddzialy()
    {
        return $this->container['jednostki_terenowe_oddzialy'];
    }

    /**
     * Sets jednostki_terenowe_oddzialy
     *
     * @param \NIP24\Model\JednostkiTerenoweOddzialy[]|null $jednostki_terenowe_oddzialy jednostki_terenowe_oddzialy
     *
     * @return self
     */
    public function setJednostkiTerenoweOddzialy($jednostki_terenowe_oddzialy)
    {
        if (is_null($jednostki_terenowe_oddzialy)) {
            throw new \InvalidArgumentException('non-nullable jednostki_terenowe_oddzialy cannot be null');
        }
        $this->container['jednostki_terenowe_oddzialy'] = $jednostki_terenowe_oddzialy;

        return $this;
    }

    /**
     * Gets umowa_statut
     *
     * @return \NIP24\Model\UmowaStatut|null
     */
    public function getUmowaStatut()
    {
        return $this->container['umowa_statut'];
    }

    /**
     * Sets umowa_statut
     *
     * @param \NIP24\Model\UmowaStatut|null $umowa_statut umowa_statut
     *
     * @return self
     */
    public function setUmowaStatut($umowa_statut)
    {
        if (is_null($umowa_statut)) {
            throw new \InvalidArgumentException('non-nullable umowa_statut cannot be null');
        }
        $this->container['umowa_statut'] = $umowa_statut;

        return $this;
    }

    /**
     * Gets pozostale_informacje
     *
     * @return \NIP24\Model\PozostaleInformacje|null
     */
    public function getPozostaleInformacje()
    {
        return $this->container['pozostale_informacje'];
    }

    /**
     * Sets pozostale_informacje
     *
     * @param \NIP24\Model\PozostaleInformacje|null $pozostale_informacje pozostale_informacje
     *
     * @return self
     */
    public function setPozostaleInformacje($pozostale_informacje)
    {
        if (is_null($pozostale_informacje)) {
            throw new \InvalidArgumentException('non-nullable pozostale_informacje cannot be null');
        }
        $this->container['pozostale_informacje'] = $pozostale_informacje;

        return $this;
    }

    /**
     * Gets wspolnicy_spzoo
     *
     * @return \NIP24\Model\WspolnicySpzoo[]|null
     */
    public function getWspolnicySpzoo()
    {
        return $this->container['wspolnicy_spzoo'];
    }

    /**
     * Sets wspolnicy_spzoo
     *
     * @param \NIP24\Model\WspolnicySpzoo[]|null $wspolnicy_spzoo wspolnicy_spzoo
     *
     * @return self
     */
    public function setWspolnicySpzoo($wspolnicy_spzoo)
    {
        if (is_null($wspolnicy_spzoo)) {
            throw new \InvalidArgumentException('non-nullable wspolnicy_spzoo cannot be null');
        }
        $this->container['wspolnicy_spzoo'] = $wspolnicy_spzoo;

        return $this;
    }

    /**
     * Gets jedyny_akcjonariusz
     *
     * @return \NIP24\Model\JedynyAkcjonariusz[]|null
     */
    public function getJedynyAkcjonariusz()
    {
        return $this->container['jedyny_akcjonariusz'];
    }

    /**
     * Sets jedyny_akcjonariusz
     *
     * @param \NIP24\Model\JedynyAkcjonariusz[]|null $jedyny_akcjonariusz jedyny_akcjonariusz
     *
     * @return self
     */
    public function setJedynyAkcjonariusz($jedyny_akcjonariusz)
    {
        if (is_null($jedyny_akcjonariusz)) {
            throw new \InvalidArgumentException('non-nullable jedyny_akcjonariusz cannot be null');
        }
        $this->container['jedyny_akcjonariusz'] = $jedyny_akcjonariusz;

        return $this;
    }

    /**
     * Gets sposob_powstania_podmiotu
     *
     * @return \NIP24\Model\SposobPowstaniaPodmiotu|null
     */
    public function getSposobPowstaniaPodmiotu()
    {
        return $this->container['sposob_powstania_podmiotu'];
    }

    /**
     * Sets sposob_powstania_podmiotu
     *
     * @param \NIP24\Model\SposobPowstaniaPodmiotu|null $sposob_powstania_podmiotu sposob_powstania_podmiotu
     *
     * @return self
     */
    public function setSposobPowstaniaPodmiotu($sposob_powstania_podmiotu)
    {
        if (is_null($sposob_powstania_podmiotu)) {
            throw new \InvalidArgumentException('non-nullable sposob_powstania_podmiotu cannot be null');
        }
        $this->container['sposob_powstania_podmiotu'] = $sposob_powstania_podmiotu;

        return $this;
    }

    /**
     * Gets kapital
     *
     * @return \NIP24\Model\Kapital|null
     */
    public function getKapital()
    {
        return $this->container['kapital'];
    }

    /**
     * Sets kapital
     *
     * @param \NIP24\Model\Kapital|null $kapital kapital
     *
     * @return self
     */
    public function setKapital($kapital)
    {
        if (is_null($kapital)) {
            throw new \InvalidArgumentException('non-nullable kapital cannot be null');
        }
        $this->container['kapital'] = $kapital;

        return $this;
    }

    /**
     * Gets emisje_akcji
     *
     * @return \NIP24\Model\EmisjeAkcji[]|null
     */
    public function getEmisjeAkcji()
    {
        return $this->container['emisje_akcji'];
    }

    /**
     * Sets emisje_akcji
     *
     * @param \NIP24\Model\EmisjeAkcji[]|null $emisje_akcji emisje_akcji
     *
     * @return self
     */
    public function setEmisjeAkcji($emisje_akcji)
    {
        if (is_null($emisje_akcji)) {
            throw new \InvalidArgumentException('non-nullable emisje_akcji cannot be null');
        }
        $this->container['emisje_akcji'] = $emisje_akcji;

        return $this;
    }

    /**
     * Gets wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych
     *
     * @return \NIP24\Model\WzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych|null
     */
    public function getWzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych()
    {
        return $this->container['wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych'];
    }

    /**
     * Sets wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych
     *
     * @param \NIP24\Model\WzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych|null $wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych
     *
     * @return self
     */
    public function setWzmiankaOPodjeciuUchwalyOEmisjachObligacjiZamiennych($wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych)
    {
        if (is_null($wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych)) {
            throw new \InvalidArgumentException('non-nullable wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych cannot be null');
        }
        $this->container['wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych'] = $wzmianka_o_podjeciu_uchwaly_o_emisjach_obligacji_zamiennych;

        return $this;
    }

    /**
     * Gets wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych
     *
     * @return \NIP24\Model\WzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych|null
     */
    public function getWzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych()
    {
        return $this->container['wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych'];
    }

    /**
     * Sets wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych
     *
     * @param \NIP24\Model\WzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych|null $wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych
     *
     * @return self
     */
    public function setWzmiankaOUpowaznieniuDoEmisjiWarrantowSubskrypcyjnych($wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych)
    {
        if (is_null($wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych)) {
            throw new \InvalidArgumentException('non-nullable wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych cannot be null');
        }
        $this->container['wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych'] = $wzmianka_o_upowaznieniu_do_emisji_warrantow_subskrypcyjnych;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


