<?php
/**
 * Dzial6
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: kontakt@nip24.pl
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * Dzial6 Class Doc Comment
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Dzial6 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Dzial6';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'postepowanie_upadlosciowe' => '\NIP24\Model\PostepowanieUpadlosciowe[]',
        'polaczenie_podzial_przeksztalcenie' => '\NIP24\Model\PolaczeniePodzialPrzeksztalcenie[]',
        'likwidacja' => '\NIP24\Model\Likwidacja[]',
        'rozwiazanie_uniewaznienie' => '\NIP24\Model\RozwiazanieUniewaznienie[]',
        'zawieszenie_wznowienie' => '\NIP24\Model\ZawieszenieWznowienie[]',
        'postepowanie_ukladowe' => '\NIP24\Model\PostepowanieUkladowe[]',
        'postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja' => '\NIP24\Model\PostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'postepowanie_upadlosciowe' => null,
        'polaczenie_podzial_przeksztalcenie' => null,
        'likwidacja' => null,
        'rozwiazanie_uniewaznienie' => null,
        'zawieszenie_wznowienie' => null,
        'postepowanie_ukladowe' => null,
        'postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'postepowanie_upadlosciowe' => false,
        'polaczenie_podzial_przeksztalcenie' => false,
        'likwidacja' => false,
        'rozwiazanie_uniewaznienie' => false,
        'zawieszenie_wznowienie' => false,
        'postepowanie_ukladowe' => false,
        'postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'postepowanie_upadlosciowe' => 'postepowanieUpadlosciowe',
        'polaczenie_podzial_przeksztalcenie' => 'polaczeniePodzialPrzeksztalcenie',
        'likwidacja' => 'likwidacja',
        'rozwiazanie_uniewaznienie' => 'rozwiazanieUniewaznienie',
        'zawieszenie_wznowienie' => 'zawieszenieWznowienie',
        'postepowanie_ukladowe' => 'postepowanieUkladowe',
        'postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja' => 'postepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'postepowanie_upadlosciowe' => 'setPostepowanieUpadlosciowe',
        'polaczenie_podzial_przeksztalcenie' => 'setPolaczeniePodzialPrzeksztalcenie',
        'likwidacja' => 'setLikwidacja',
        'rozwiazanie_uniewaznienie' => 'setRozwiazanieUniewaznienie',
        'zawieszenie_wznowienie' => 'setZawieszenieWznowienie',
        'postepowanie_ukladowe' => 'setPostepowanieUkladowe',
        'postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja' => 'setPostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'postepowanie_upadlosciowe' => 'getPostepowanieUpadlosciowe',
        'polaczenie_podzial_przeksztalcenie' => 'getPolaczeniePodzialPrzeksztalcenie',
        'likwidacja' => 'getLikwidacja',
        'rozwiazanie_uniewaznienie' => 'getRozwiazanieUniewaznienie',
        'zawieszenie_wznowienie' => 'getZawieszenieWznowienie',
        'postepowanie_ukladowe' => 'getPostepowanieUkladowe',
        'postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja' => 'getPostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('postepowanie_upadlosciowe', $data ?? [], null);
        $this->setIfExists('polaczenie_podzial_przeksztalcenie', $data ?? [], null);
        $this->setIfExists('likwidacja', $data ?? [], null);
        $this->setIfExists('rozwiazanie_uniewaznienie', $data ?? [], null);
        $this->setIfExists('zawieszenie_wznowienie', $data ?? [], null);
        $this->setIfExists('postepowanie_ukladowe', $data ?? [], null);
        $this->setIfExists('postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets postepowanie_upadlosciowe
     *
     * @return \NIP24\Model\PostepowanieUpadlosciowe[]|null
     */
    public function getPostepowanieUpadlosciowe()
    {
        return $this->container['postepowanie_upadlosciowe'];
    }

    /**
     * Sets postepowanie_upadlosciowe
     *
     * @param \NIP24\Model\PostepowanieUpadlosciowe[]|null $postepowanie_upadlosciowe postepowanie_upadlosciowe
     *
     * @return self
     */
    public function setPostepowanieUpadlosciowe($postepowanie_upadlosciowe)
    {
        if (is_null($postepowanie_upadlosciowe)) {
            throw new \InvalidArgumentException('non-nullable postepowanie_upadlosciowe cannot be null');
        }
        $this->container['postepowanie_upadlosciowe'] = $postepowanie_upadlosciowe;

        return $this;
    }

    /**
     * Gets polaczenie_podzial_przeksztalcenie
     *
     * @return \NIP24\Model\PolaczeniePodzialPrzeksztalcenie[]|null
     */
    public function getPolaczeniePodzialPrzeksztalcenie()
    {
        return $this->container['polaczenie_podzial_przeksztalcenie'];
    }

    /**
     * Sets polaczenie_podzial_przeksztalcenie
     *
     * @param \NIP24\Model\PolaczeniePodzialPrzeksztalcenie[]|null $polaczenie_podzial_przeksztalcenie polaczenie_podzial_przeksztalcenie
     *
     * @return self
     */
    public function setPolaczeniePodzialPrzeksztalcenie($polaczenie_podzial_przeksztalcenie)
    {
        if (is_null($polaczenie_podzial_przeksztalcenie)) {
            throw new \InvalidArgumentException('non-nullable polaczenie_podzial_przeksztalcenie cannot be null');
        }
        $this->container['polaczenie_podzial_przeksztalcenie'] = $polaczenie_podzial_przeksztalcenie;

        return $this;
    }

    /**
     * Gets likwidacja
     *
     * @return \NIP24\Model\Likwidacja[]|null
     */
    public function getLikwidacja()
    {
        return $this->container['likwidacja'];
    }

    /**
     * Sets likwidacja
     *
     * @param \NIP24\Model\Likwidacja[]|null $likwidacja likwidacja
     *
     * @return self
     */
    public function setLikwidacja($likwidacja)
    {
        if (is_null($likwidacja)) {
            throw new \InvalidArgumentException('non-nullable likwidacja cannot be null');
        }
        $this->container['likwidacja'] = $likwidacja;

        return $this;
    }

    /**
     * Gets rozwiazanie_uniewaznienie
     *
     * @return \NIP24\Model\RozwiazanieUniewaznienie[]|null
     */
    public function getRozwiazanieUniewaznienie()
    {
        return $this->container['rozwiazanie_uniewaznienie'];
    }

    /**
     * Sets rozwiazanie_uniewaznienie
     *
     * @param \NIP24\Model\RozwiazanieUniewaznienie[]|null $rozwiazanie_uniewaznienie rozwiazanie_uniewaznienie
     *
     * @return self
     */
    public function setRozwiazanieUniewaznienie($rozwiazanie_uniewaznienie)
    {
        if (is_null($rozwiazanie_uniewaznienie)) {
            throw new \InvalidArgumentException('non-nullable rozwiazanie_uniewaznienie cannot be null');
        }
        $this->container['rozwiazanie_uniewaznienie'] = $rozwiazanie_uniewaznienie;

        return $this;
    }

    /**
     * Gets zawieszenie_wznowienie
     *
     * @return \NIP24\Model\ZawieszenieWznowienie[]|null
     */
    public function getZawieszenieWznowienie()
    {
        return $this->container['zawieszenie_wznowienie'];
    }

    /**
     * Sets zawieszenie_wznowienie
     *
     * @param \NIP24\Model\ZawieszenieWznowienie[]|null $zawieszenie_wznowienie zawieszenie_wznowienie
     *
     * @return self
     */
    public function setZawieszenieWznowienie($zawieszenie_wznowienie)
    {
        if (is_null($zawieszenie_wznowienie)) {
            throw new \InvalidArgumentException('non-nullable zawieszenie_wznowienie cannot be null');
        }
        $this->container['zawieszenie_wznowienie'] = $zawieszenie_wznowienie;

        return $this;
    }

    /**
     * Gets postepowanie_ukladowe
     *
     * @return \NIP24\Model\PostepowanieUkladowe[]|null
     */
    public function getPostepowanieUkladowe()
    {
        return $this->container['postepowanie_ukladowe'];
    }

    /**
     * Sets postepowanie_ukladowe
     *
     * @param \NIP24\Model\PostepowanieUkladowe[]|null $postepowanie_ukladowe postepowanie_ukladowe
     *
     * @return self
     */
    public function setPostepowanieUkladowe($postepowanie_ukladowe)
    {
        if (is_null($postepowanie_ukladowe)) {
            throw new \InvalidArgumentException('non-nullable postepowanie_ukladowe cannot be null');
        }
        $this->container['postepowanie_ukladowe'] = $postepowanie_ukladowe;

        return $this;
    }

    /**
     * Gets postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja
     *
     * @return \NIP24\Model\PostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja[]|null
     */
    public function getPostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja()
    {
        return $this->container['postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja'];
    }

    /**
     * Sets postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja
     *
     * @param \NIP24\Model\PostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja[]|null $postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja
     *
     * @return self
     */
    public function setPostepowanieRestrukturyzacyjneNaprawczePrzymusowaRestrukturyzacja($postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja)
    {
        if (is_null($postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja)) {
            throw new \InvalidArgumentException('non-nullable postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja cannot be null');
        }
        $this->container['postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja'] = $postepowanie_restrukturyzacyjne_naprawcze_przymusowa_restrukturyzacja;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


