<?php
/**
 * Dzial2
 *
 * PHP version 5
 *
 * @category Class
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * Dzial2 Class Doc Comment
 *
 * @category Class
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Dzial2 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Dzial2';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'organ_nadzoru' => '\NIP24\Model\OrganNadzoru[]',
'reprezentacja' => '\NIP24\Model\Reprezentacja',
'prokurenci' => '\NIP24\Model\Prokurenci[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'organ_nadzoru' => null,
'reprezentacja' => null,
'prokurenci' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'organ_nadzoru' => 'organNadzoru',
'reprezentacja' => 'reprezentacja',
'prokurenci' => 'prokurenci'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'organ_nadzoru' => 'setOrganNadzoru',
'reprezentacja' => 'setReprezentacja',
'prokurenci' => 'setProkurenci'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'organ_nadzoru' => 'getOrganNadzoru',
'reprezentacja' => 'getReprezentacja',
'prokurenci' => 'getProkurenci'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['organ_nadzoru'] = isset($data['organ_nadzoru']) ? $data['organ_nadzoru'] : null;
        $this->container['reprezentacja'] = isset($data['reprezentacja']) ? $data['reprezentacja'] : null;
        $this->container['prokurenci'] = isset($data['prokurenci']) ? $data['prokurenci'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets organ_nadzoru
     *
     * @return \NIP24\Model\OrganNadzoru[]
     */
    public function getOrganNadzoru()
    {
        return $this->container['organ_nadzoru'];
    }

    /**
     * Sets organ_nadzoru
     *
     * @param \NIP24\Model\OrganNadzoru[] $organ_nadzoru organ_nadzoru
     *
     * @return $this
     */
    public function setOrganNadzoru($organ_nadzoru)
    {
        $this->container['organ_nadzoru'] = $organ_nadzoru;

        return $this;
    }

    /**
     * Gets reprezentacja
     *
     * @return \NIP24\Model\Reprezentacja
     */
    public function getReprezentacja()
    {
        return $this->container['reprezentacja'];
    }

    /**
     * Sets reprezentacja
     *
     * @param \NIP24\Model\Reprezentacja $reprezentacja reprezentacja
     *
     * @return $this
     */
    public function setReprezentacja($reprezentacja)
    {
        $this->container['reprezentacja'] = $reprezentacja;

        return $this;
    }

    /**
     * Gets prokurenci
     *
     * @return \NIP24\Model\Prokurenci[]
     */
    public function getProkurenci()
    {
        return $this->container['prokurenci'];
    }

    /**
     * Sets prokurenci
     *
     * @param \NIP24\Model\Prokurenci[] $prokurenci prokurenci
     *
     * @return $this
     */
    public function setProkurenci($prokurenci)
    {
        $this->container['prokurenci'] = $prokurenci;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
