<?php
/**
 * FakturaZaliczkowa
 *
 * PHP version 5
 *
 * @category Class
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * FakturaZaliczkowa Class Doc Comment
 *
 * @category Class
 * @description Numery faktur zaliczkowych lub ich numery KSeF, jeśli zostały wystawione z użyciem KSeF
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FakturaZaliczkowa implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FakturaZaliczkowa';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'nr_kse_fzn' => '\NIP24\Model\TWybor1',
'nr_fa_zaliczkowej' => '\NIP24\Model\TZnakowy',
'nr_kse_ffa_zaliczkowej' => '\NIP24\Model\TNumerKSeF'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'nr_kse_fzn' => null,
'nr_fa_zaliczkowej' => null,
'nr_kse_ffa_zaliczkowej' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'nr_kse_fzn' => 'NrKSeFZN',
'nr_fa_zaliczkowej' => 'NrFaZaliczkowej',
'nr_kse_ffa_zaliczkowej' => 'NrKSeFFaZaliczkowej'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'nr_kse_fzn' => 'setNrKseFzn',
'nr_fa_zaliczkowej' => 'setNrFaZaliczkowej',
'nr_kse_ffa_zaliczkowej' => 'setNrKseFfaZaliczkowej'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'nr_kse_fzn' => 'getNrKseFzn',
'nr_fa_zaliczkowej' => 'getNrFaZaliczkowej',
'nr_kse_ffa_zaliczkowej' => 'getNrKseFfaZaliczkowej'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['nr_kse_fzn'] = isset($data['nr_kse_fzn']) ? $data['nr_kse_fzn'] : null;
        $this->container['nr_fa_zaliczkowej'] = isset($data['nr_fa_zaliczkowej']) ? $data['nr_fa_zaliczkowej'] : null;
        $this->container['nr_kse_ffa_zaliczkowej'] = isset($data['nr_kse_ffa_zaliczkowej']) ? $data['nr_kse_ffa_zaliczkowej'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nr_kse_fzn
     *
     * @return \NIP24\Model\TWybor1
     */
    public function getNrKseFzn()
    {
        return $this->container['nr_kse_fzn'];
    }

    /**
     * Sets nr_kse_fzn
     *
     * @param \NIP24\Model\TWybor1 $nr_kse_fzn nr_kse_fzn
     *
     * @return $this
     */
    public function setNrKseFzn($nr_kse_fzn)
    {
        $this->container['nr_kse_fzn'] = $nr_kse_fzn;

        return $this;
    }

    /**
     * Gets nr_fa_zaliczkowej
     *
     * @return \NIP24\Model\TZnakowy
     */
    public function getNrFaZaliczkowej()
    {
        return $this->container['nr_fa_zaliczkowej'];
    }

    /**
     * Sets nr_fa_zaliczkowej
     *
     * @param \NIP24\Model\TZnakowy $nr_fa_zaliczkowej nr_fa_zaliczkowej
     *
     * @return $this
     */
    public function setNrFaZaliczkowej($nr_fa_zaliczkowej)
    {
        $this->container['nr_fa_zaliczkowej'] = $nr_fa_zaliczkowej;

        return $this;
    }

    /**
     * Gets nr_kse_ffa_zaliczkowej
     *
     * @return \NIP24\Model\TNumerKSeF
     */
    public function getNrKseFfaZaliczkowej()
    {
        return $this->container['nr_kse_ffa_zaliczkowej'];
    }

    /**
     * Sets nr_kse_ffa_zaliczkowej
     *
     * @param \NIP24\Model\TNumerKSeF $nr_kse_ffa_zaliczkowej nr_kse_ffa_zaliczkowej
     *
     * @return $this
     */
    public function setNrKseFfaZaliczkowej($nr_kse_ffa_zaliczkowej)
    {
        $this->container['nr_kse_ffa_zaliczkowej'] = $nr_kse_ffa_zaliczkowej;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
