<?php
/**
 * Likwidacja
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: kontakt@nip24.pl
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * Likwidacja Class Doc Comment
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Likwidacja implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Likwidacja';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'otwarcie_likwidacji' => 'string',
        'sposob_reprezentacji_podmiotu_przez_likwidatorow' => 'string',
        'likwidatorzy' => '\NIP24\Model\Osoba[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'otwarcie_likwidacji' => null,
        'sposob_reprezentacji_podmiotu_przez_likwidatorow' => null,
        'likwidatorzy' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'otwarcie_likwidacji' => false,
        'sposob_reprezentacji_podmiotu_przez_likwidatorow' => false,
        'likwidatorzy' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'otwarcie_likwidacji' => 'otwarcieLikwidacji',
        'sposob_reprezentacji_podmiotu_przez_likwidatorow' => 'sposobReprezentacjiPodmiotuPrzezLikwidatorow',
        'likwidatorzy' => 'likwidatorzy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'otwarcie_likwidacji' => 'setOtwarcieLikwidacji',
        'sposob_reprezentacji_podmiotu_przez_likwidatorow' => 'setSposobReprezentacjiPodmiotuPrzezLikwidatorow',
        'likwidatorzy' => 'setLikwidatorzy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'otwarcie_likwidacji' => 'getOtwarcieLikwidacji',
        'sposob_reprezentacji_podmiotu_przez_likwidatorow' => 'getSposobReprezentacjiPodmiotuPrzezLikwidatorow',
        'likwidatorzy' => 'getLikwidatorzy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('otwarcie_likwidacji', $data ?? [], null);
        $this->setIfExists('sposob_reprezentacji_podmiotu_przez_likwidatorow', $data ?? [], null);
        $this->setIfExists('likwidatorzy', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets otwarcie_likwidacji
     *
     * @return string|null
     */
    public function getOtwarcieLikwidacji()
    {
        return $this->container['otwarcie_likwidacji'];
    }

    /**
     * Sets otwarcie_likwidacji
     *
     * @param string|null $otwarcie_likwidacji otwarcie_likwidacji
     *
     * @return self
     */
    public function setOtwarcieLikwidacji($otwarcie_likwidacji)
    {
        if (is_null($otwarcie_likwidacji)) {
            throw new \InvalidArgumentException('non-nullable otwarcie_likwidacji cannot be null');
        }
        $this->container['otwarcie_likwidacji'] = $otwarcie_likwidacji;

        return $this;
    }

    /**
     * Gets sposob_reprezentacji_podmiotu_przez_likwidatorow
     *
     * @return string|null
     */
    public function getSposobReprezentacjiPodmiotuPrzezLikwidatorow()
    {
        return $this->container['sposob_reprezentacji_podmiotu_przez_likwidatorow'];
    }

    /**
     * Sets sposob_reprezentacji_podmiotu_przez_likwidatorow
     *
     * @param string|null $sposob_reprezentacji_podmiotu_przez_likwidatorow sposob_reprezentacji_podmiotu_przez_likwidatorow
     *
     * @return self
     */
    public function setSposobReprezentacjiPodmiotuPrzezLikwidatorow($sposob_reprezentacji_podmiotu_przez_likwidatorow)
    {
        if (is_null($sposob_reprezentacji_podmiotu_przez_likwidatorow)) {
            throw new \InvalidArgumentException('non-nullable sposob_reprezentacji_podmiotu_przez_likwidatorow cannot be null');
        }
        $this->container['sposob_reprezentacji_podmiotu_przez_likwidatorow'] = $sposob_reprezentacji_podmiotu_przez_likwidatorow;

        return $this;
    }

    /**
     * Gets likwidatorzy
     *
     * @return \NIP24\Model\Osoba[]|null
     */
    public function getLikwidatorzy()
    {
        return $this->container['likwidatorzy'];
    }

    /**
     * Sets likwidatorzy
     *
     * @param \NIP24\Model\Osoba[]|null $likwidatorzy likwidatorzy
     *
     * @return self
     */
    public function setLikwidatorzy($likwidatorzy)
    {
        if (is_null($likwidatorzy)) {
            throw new \InvalidArgumentException('non-nullable likwidatorzy cannot be null');
        }
        $this->container['likwidatorzy'] = $likwidatorzy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


