<?php
/**
 * Odpis
 *
 * PHP version 5
 *
 * @category Class
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * Odpis Class Doc Comment
 *
 * @category Class
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Odpis implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Odpis';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'rodzaj' => '\NIP24\Model\RodzajOdpisu',
'naglowek_a' => '\NIP24\Model\NaglowekA',
'dane' => '\NIP24\Model\Dane'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'rodzaj' => null,
'naglowek_a' => null,
'dane' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rodzaj' => 'rodzaj',
'naglowek_a' => 'naglowekA',
'dane' => 'dane'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rodzaj' => 'setRodzaj',
'naglowek_a' => 'setNaglowekA',
'dane' => 'setDane'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rodzaj' => 'getRodzaj',
'naglowek_a' => 'getNaglowekA',
'dane' => 'getDane'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['rodzaj'] = isset($data['rodzaj']) ? $data['rodzaj'] : null;
        $this->container['naglowek_a'] = isset($data['naglowek_a']) ? $data['naglowek_a'] : null;
        $this->container['dane'] = isset($data['dane']) ? $data['dane'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['rodzaj'] === null) {
            $invalidProperties[] = "'rodzaj' can't be null";
        }
        if ($this->container['dane'] === null) {
            $invalidProperties[] = "'dane' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rodzaj
     *
     * @return \NIP24\Model\RodzajOdpisu
     */
    public function getRodzaj()
    {
        return $this->container['rodzaj'];
    }

    /**
     * Sets rodzaj
     *
     * @param \NIP24\Model\RodzajOdpisu $rodzaj rodzaj
     *
     * @return $this
     */
    public function setRodzaj($rodzaj)
    {
        $this->container['rodzaj'] = $rodzaj;

        return $this;
    }

    /**
     * Gets naglowek_a
     *
     * @return \NIP24\Model\NaglowekA
     */
    public function getNaglowekA()
    {
        return $this->container['naglowek_a'];
    }

    /**
     * Sets naglowek_a
     *
     * @param \NIP24\Model\NaglowekA $naglowek_a naglowek_a
     *
     * @return $this
     */
    public function setNaglowekA($naglowek_a)
    {
        $this->container['naglowek_a'] = $naglowek_a;

        return $this;
    }

    /**
     * Gets dane
     *
     * @return \NIP24\Model\Dane
     */
    public function getDane()
    {
        return $this->container['dane'];
    }

    /**
     * Sets dane
     *
     * @param \NIP24\Model\Dane $dane dane
     *
     * @return $this
     */
    public function setDane($dane)
    {
        $this->container['dane'] = $dane;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
