<?php
/**
 * PozostaleInformacje
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: kontakt@nip24.pl
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * PozostaleInformacje Class Doc Comment
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PozostaleInformacje implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PozostaleInformacje';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'czas_na_jaki_utworzony_zostal_podmiot' => 'string',
        'informacja_o_liczbie_udzialow' => 'string',
        'czy_umowa_statut_przyznaje_uprawnienia_osobiste' => 'bool',
        'czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'czas_na_jaki_utworzony_zostal_podmiot' => null,
        'informacja_o_liczbie_udzialow' => null,
        'czy_umowa_statut_przyznaje_uprawnienia_osobiste' => null,
        'czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'czas_na_jaki_utworzony_zostal_podmiot' => false,
        'informacja_o_liczbie_udzialow' => false,
        'czy_umowa_statut_przyznaje_uprawnienia_osobiste' => false,
        'czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'czas_na_jaki_utworzony_zostal_podmiot' => 'czasNaJakiUtworzonyZostalPodmiot',
        'informacja_o_liczbie_udzialow' => 'informacjaOLiczbieUdzialow',
        'czy_umowa_statut_przyznaje_uprawnienia_osobiste' => 'czyUmowaStatutPrzyznajeUprawnieniaOsobiste',
        'czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku' => 'czyObligatoriuszeMajaPrawoDoUdzialuWZysku'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'czas_na_jaki_utworzony_zostal_podmiot' => 'setCzasNaJakiUtworzonyZostalPodmiot',
        'informacja_o_liczbie_udzialow' => 'setInformacjaOLiczbieUdzialow',
        'czy_umowa_statut_przyznaje_uprawnienia_osobiste' => 'setCzyUmowaStatutPrzyznajeUprawnieniaOsobiste',
        'czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku' => 'setCzyObligatoriuszeMajaPrawoDoUdzialuWZysku'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'czas_na_jaki_utworzony_zostal_podmiot' => 'getCzasNaJakiUtworzonyZostalPodmiot',
        'informacja_o_liczbie_udzialow' => 'getInformacjaOLiczbieUdzialow',
        'czy_umowa_statut_przyznaje_uprawnienia_osobiste' => 'getCzyUmowaStatutPrzyznajeUprawnieniaOsobiste',
        'czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku' => 'getCzyObligatoriuszeMajaPrawoDoUdzialuWZysku'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('czas_na_jaki_utworzony_zostal_podmiot', $data ?? [], null);
        $this->setIfExists('informacja_o_liczbie_udzialow', $data ?? [], null);
        $this->setIfExists('czy_umowa_statut_przyznaje_uprawnienia_osobiste', $data ?? [], null);
        $this->setIfExists('czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets czas_na_jaki_utworzony_zostal_podmiot
     *
     * @return string|null
     */
    public function getCzasNaJakiUtworzonyZostalPodmiot()
    {
        return $this->container['czas_na_jaki_utworzony_zostal_podmiot'];
    }

    /**
     * Sets czas_na_jaki_utworzony_zostal_podmiot
     *
     * @param string|null $czas_na_jaki_utworzony_zostal_podmiot czas_na_jaki_utworzony_zostal_podmiot
     *
     * @return self
     */
    public function setCzasNaJakiUtworzonyZostalPodmiot($czas_na_jaki_utworzony_zostal_podmiot)
    {
        if (is_null($czas_na_jaki_utworzony_zostal_podmiot)) {
            throw new \InvalidArgumentException('non-nullable czas_na_jaki_utworzony_zostal_podmiot cannot be null');
        }
        $this->container['czas_na_jaki_utworzony_zostal_podmiot'] = $czas_na_jaki_utworzony_zostal_podmiot;

        return $this;
    }

    /**
     * Gets informacja_o_liczbie_udzialow
     *
     * @return string|null
     */
    public function getInformacjaOLiczbieUdzialow()
    {
        return $this->container['informacja_o_liczbie_udzialow'];
    }

    /**
     * Sets informacja_o_liczbie_udzialow
     *
     * @param string|null $informacja_o_liczbie_udzialow informacja_o_liczbie_udzialow
     *
     * @return self
     */
    public function setInformacjaOLiczbieUdzialow($informacja_o_liczbie_udzialow)
    {
        if (is_null($informacja_o_liczbie_udzialow)) {
            throw new \InvalidArgumentException('non-nullable informacja_o_liczbie_udzialow cannot be null');
        }
        $this->container['informacja_o_liczbie_udzialow'] = $informacja_o_liczbie_udzialow;

        return $this;
    }

    /**
     * Gets czy_umowa_statut_przyznaje_uprawnienia_osobiste
     *
     * @return bool|null
     */
    public function getCzyUmowaStatutPrzyznajeUprawnieniaOsobiste()
    {
        return $this->container['czy_umowa_statut_przyznaje_uprawnienia_osobiste'];
    }

    /**
     * Sets czy_umowa_statut_przyznaje_uprawnienia_osobiste
     *
     * @param bool|null $czy_umowa_statut_przyznaje_uprawnienia_osobiste czy_umowa_statut_przyznaje_uprawnienia_osobiste
     *
     * @return self
     */
    public function setCzyUmowaStatutPrzyznajeUprawnieniaOsobiste($czy_umowa_statut_przyznaje_uprawnienia_osobiste)
    {
        if (is_null($czy_umowa_statut_przyznaje_uprawnienia_osobiste)) {
            throw new \InvalidArgumentException('non-nullable czy_umowa_statut_przyznaje_uprawnienia_osobiste cannot be null');
        }
        $this->container['czy_umowa_statut_przyznaje_uprawnienia_osobiste'] = $czy_umowa_statut_przyznaje_uprawnienia_osobiste;

        return $this;
    }

    /**
     * Gets czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku
     *
     * @return bool|null
     */
    public function getCzyObligatoriuszeMajaPrawoDoUdzialuWZysku()
    {
        return $this->container['czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku'];
    }

    /**
     * Sets czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku
     *
     * @param bool|null $czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku
     *
     * @return self
     */
    public function setCzyObligatoriuszeMajaPrawoDoUdzialuWZysku($czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku)
    {
        if (is_null($czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku)) {
            throw new \InvalidArgumentException('non-nullable czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku cannot be null');
        }
        $this->container['czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku'] = $czy_obligatoriusze_maja_prawo_do_udzialu_w_zysku;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


