<?php
/**
 * Przewoznik
 *
 * PHP version 5
 *
 * @category Class
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * Przewoznik Class Doc Comment
 *
 * @category Class
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Przewoznik implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Przewoznik';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'dane_identyfikacyjne' => '\NIP24\Model\TPodmiot2',
'adres_przewoznika' => '\NIP24\Model\TAdres'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'dane_identyfikacyjne' => null,
'adres_przewoznika' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dane_identyfikacyjne' => 'DaneIdentyfikacyjne',
'adres_przewoznika' => 'AdresPrzewoznika'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dane_identyfikacyjne' => 'setDaneIdentyfikacyjne',
'adres_przewoznika' => 'setAdresPrzewoznika'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dane_identyfikacyjne' => 'getDaneIdentyfikacyjne',
'adres_przewoznika' => 'getAdresPrzewoznika'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['dane_identyfikacyjne'] = isset($data['dane_identyfikacyjne']) ? $data['dane_identyfikacyjne'] : null;
        $this->container['adres_przewoznika'] = isset($data['adres_przewoznika']) ? $data['adres_przewoznika'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['dane_identyfikacyjne'] === null) {
            $invalidProperties[] = "'dane_identyfikacyjne' can't be null";
        }
        if ($this->container['adres_przewoznika'] === null) {
            $invalidProperties[] = "'adres_przewoznika' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dane_identyfikacyjne
     *
     * @return \NIP24\Model\TPodmiot2
     */
    public function getDaneIdentyfikacyjne()
    {
        return $this->container['dane_identyfikacyjne'];
    }

    /**
     * Sets dane_identyfikacyjne
     *
     * @param \NIP24\Model\TPodmiot2 $dane_identyfikacyjne dane_identyfikacyjne
     *
     * @return $this
     */
    public function setDaneIdentyfikacyjne($dane_identyfikacyjne)
    {
        $this->container['dane_identyfikacyjne'] = $dane_identyfikacyjne;

        return $this;
    }

    /**
     * Gets adres_przewoznika
     *
     * @return \NIP24\Model\TAdres
     */
    public function getAdresPrzewoznika()
    {
        return $this->container['adres_przewoznika'];
    }

    /**
     * Sets adres_przewoznika
     *
     * @param \NIP24\Model\TAdres $adres_przewoznika adres_przewoznika
     *
     * @return $this
     */
    public function setAdresPrzewoznika($adres_przewoznika)
    {
        $this->container['adres_przewoznika'] = $adres_przewoznika;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
