<?php
/**
 * RozwiazanieUniewaznienie
 *
 * PHP version 5
 *
 * @category Class
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.5
 * Contact: kontakt@nip24.pl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * RozwiazanieUniewaznienie Class Doc Comment
 *
 * @category Class
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RozwiazanieUniewaznienie implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RozwiazanieUniewaznienie';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'okreslenie_okolicznosci' => 'string',
'informacja_o_rozwiazaniu_uniewaznieniu' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'okreslenie_okolicznosci' => null,
'informacja_o_rozwiazaniu_uniewaznieniu' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'okreslenie_okolicznosci' => 'okreslenieOkolicznosci',
'informacja_o_rozwiazaniu_uniewaznieniu' => 'informacjaORozwiazaniuUniewaznieniu'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'okreslenie_okolicznosci' => 'setOkreslenieOkolicznosci',
'informacja_o_rozwiazaniu_uniewaznieniu' => 'setInformacjaORozwiazaniuUniewaznieniu'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'okreslenie_okolicznosci' => 'getOkreslenieOkolicznosci',
'informacja_o_rozwiazaniu_uniewaznieniu' => 'getInformacjaORozwiazaniuUniewaznieniu'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['okreslenie_okolicznosci'] = isset($data['okreslenie_okolicznosci']) ? $data['okreslenie_okolicznosci'] : null;
        $this->container['informacja_o_rozwiazaniu_uniewaznieniu'] = isset($data['informacja_o_rozwiazaniu_uniewaznieniu']) ? $data['informacja_o_rozwiazaniu_uniewaznieniu'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets okreslenie_okolicznosci
     *
     * @return string
     */
    public function getOkreslenieOkolicznosci()
    {
        return $this->container['okreslenie_okolicznosci'];
    }

    /**
     * Sets okreslenie_okolicznosci
     *
     * @param string $okreslenie_okolicznosci okreslenie_okolicznosci
     *
     * @return $this
     */
    public function setOkreslenieOkolicznosci($okreslenie_okolicznosci)
    {
        $this->container['okreslenie_okolicznosci'] = $okreslenie_okolicznosci;

        return $this;
    }

    /**
     * Gets informacja_o_rozwiazaniu_uniewaznieniu
     *
     * @return string
     */
    public function getInformacjaORozwiazaniuUniewaznieniu()
    {
        return $this->container['informacja_o_rozwiazaniu_uniewaznieniu'];
    }

    /**
     * Sets informacja_o_rozwiazaniu_uniewaznieniu
     *
     * @param string $informacja_o_rozwiazaniu_uniewaznieniu informacja_o_rozwiazaniu_uniewaznieniu
     *
     * @return $this
     */
    public function setInformacjaORozwiazaniuUniewaznieniu($informacja_o_rozwiazaniu_uniewaznieniu)
    {
        $this->container['informacja_o_rozwiazaniu_uniewaznieniu'] = $informacja_o_rozwiazaniu_uniewaznieniu;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
