<?php
/**
 * SiedzibaIAdres
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: kontakt@nip24.pl
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * SiedzibaIAdres Class Doc Comment
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SiedzibaIAdres implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SiedzibaIAdres';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'adres_poczty_elektronicznej' => 'string',
        'adres_strony_internetowej' => 'string',
        'siedziba' => '\NIP24\Model\Siedziba',
        'adres' => '\NIP24\Model\Adres'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'adres_poczty_elektronicznej' => null,
        'adres_strony_internetowej' => null,
        'siedziba' => null,
        'adres' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'adres_poczty_elektronicznej' => false,
        'adres_strony_internetowej' => false,
        'siedziba' => false,
        'adres' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'adres_poczty_elektronicznej' => 'adresPocztyElektronicznej',
        'adres_strony_internetowej' => 'adresStronyInternetowej',
        'siedziba' => 'siedziba',
        'adres' => 'adres'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'adres_poczty_elektronicznej' => 'setAdresPocztyElektronicznej',
        'adres_strony_internetowej' => 'setAdresStronyInternetowej',
        'siedziba' => 'setSiedziba',
        'adres' => 'setAdres'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'adres_poczty_elektronicznej' => 'getAdresPocztyElektronicznej',
        'adres_strony_internetowej' => 'getAdresStronyInternetowej',
        'siedziba' => 'getSiedziba',
        'adres' => 'getAdres'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('adres_poczty_elektronicznej', $data ?? [], null);
        $this->setIfExists('adres_strony_internetowej', $data ?? [], null);
        $this->setIfExists('siedziba', $data ?? [], null);
        $this->setIfExists('adres', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets adres_poczty_elektronicznej
     *
     * @return string|null
     */
    public function getAdresPocztyElektronicznej()
    {
        return $this->container['adres_poczty_elektronicznej'];
    }

    /**
     * Sets adres_poczty_elektronicznej
     *
     * @param string|null $adres_poczty_elektronicznej adres_poczty_elektronicznej
     *
     * @return self
     */
    public function setAdresPocztyElektronicznej($adres_poczty_elektronicznej)
    {
        if (is_null($adres_poczty_elektronicznej)) {
            throw new \InvalidArgumentException('non-nullable adres_poczty_elektronicznej cannot be null');
        }
        $this->container['adres_poczty_elektronicznej'] = $adres_poczty_elektronicznej;

        return $this;
    }

    /**
     * Gets adres_strony_internetowej
     *
     * @return string|null
     */
    public function getAdresStronyInternetowej()
    {
        return $this->container['adres_strony_internetowej'];
    }

    /**
     * Sets adres_strony_internetowej
     *
     * @param string|null $adres_strony_internetowej adres_strony_internetowej
     *
     * @return self
     */
    public function setAdresStronyInternetowej($adres_strony_internetowej)
    {
        if (is_null($adres_strony_internetowej)) {
            throw new \InvalidArgumentException('non-nullable adres_strony_internetowej cannot be null');
        }
        $this->container['adres_strony_internetowej'] = $adres_strony_internetowej;

        return $this;
    }

    /**
     * Gets siedziba
     *
     * @return \NIP24\Model\Siedziba|null
     */
    public function getSiedziba()
    {
        return $this->container['siedziba'];
    }

    /**
     * Sets siedziba
     *
     * @param \NIP24\Model\Siedziba|null $siedziba siedziba
     *
     * @return self
     */
    public function setSiedziba($siedziba)
    {
        if (is_null($siedziba)) {
            throw new \InvalidArgumentException('non-nullable siedziba cannot be null');
        }
        $this->container['siedziba'] = $siedziba;

        return $this;
    }

    /**
     * Gets adres
     *
     * @return \NIP24\Model\Adres|null
     */
    public function getAdres()
    {
        return $this->container['adres'];
    }

    /**
     * Sets adres
     *
     * @param \NIP24\Model\Adres|null $adres adres
     *
     * @return self
     */
    public function setAdres($adres)
    {
        if (is_null($adres)) {
            throw new \InvalidArgumentException('non-nullable adres cannot be null');
        }
        $this->container['adres'] = $adres;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


