<?php
/**
 * SposobPowstaniaPodmiotu
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: kontakt@nip24.pl
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * SposobPowstaniaPodmiotu Class Doc Comment
 *
 * @category Class
 * @description Tylko dla spółki S.A. występuje atrybut
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SposobPowstaniaPodmiotu implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SposobPowstaniaPodmiotu';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'okolicznosci_powstania' => 'string',
        'opis_sposobu_powstania_informacja_o_uchwale' => 'string',
        'nr_data_decyzji_prezesa_uoki_k' => 'string',
        'podmioty' => '\NIP24\Model\Podmioty[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'okolicznosci_powstania' => null,
        'opis_sposobu_powstania_informacja_o_uchwale' => null,
        'nr_data_decyzji_prezesa_uoki_k' => null,
        'podmioty' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'okolicznosci_powstania' => false,
        'opis_sposobu_powstania_informacja_o_uchwale' => false,
        'nr_data_decyzji_prezesa_uoki_k' => false,
        'podmioty' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'okolicznosci_powstania' => 'okolicznosciPowstania',
        'opis_sposobu_powstania_informacja_o_uchwale' => 'opisSposobuPowstaniaInformacjaOUchwale',
        'nr_data_decyzji_prezesa_uoki_k' => 'nrDataDecyzjiPrezesaUOKiK',
        'podmioty' => 'podmioty'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'okolicznosci_powstania' => 'setOkolicznosciPowstania',
        'opis_sposobu_powstania_informacja_o_uchwale' => 'setOpisSposobuPowstaniaInformacjaOUchwale',
        'nr_data_decyzji_prezesa_uoki_k' => 'setNrDataDecyzjiPrezesaUokiK',
        'podmioty' => 'setPodmioty'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'okolicznosci_powstania' => 'getOkolicznosciPowstania',
        'opis_sposobu_powstania_informacja_o_uchwale' => 'getOpisSposobuPowstaniaInformacjaOUchwale',
        'nr_data_decyzji_prezesa_uoki_k' => 'getNrDataDecyzjiPrezesaUokiK',
        'podmioty' => 'getPodmioty'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('okolicznosci_powstania', $data ?? [], null);
        $this->setIfExists('opis_sposobu_powstania_informacja_o_uchwale', $data ?? [], null);
        $this->setIfExists('nr_data_decyzji_prezesa_uoki_k', $data ?? [], null);
        $this->setIfExists('podmioty', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets okolicznosci_powstania
     *
     * @return string|null
     */
    public function getOkolicznosciPowstania()
    {
        return $this->container['okolicznosci_powstania'];
    }

    /**
     * Sets okolicznosci_powstania
     *
     * @param string|null $okolicznosci_powstania okolicznosci_powstania
     *
     * @return self
     */
    public function setOkolicznosciPowstania($okolicznosci_powstania)
    {
        if (is_null($okolicznosci_powstania)) {
            throw new \InvalidArgumentException('non-nullable okolicznosci_powstania cannot be null');
        }
        $this->container['okolicznosci_powstania'] = $okolicznosci_powstania;

        return $this;
    }

    /**
     * Gets opis_sposobu_powstania_informacja_o_uchwale
     *
     * @return string|null
     */
    public function getOpisSposobuPowstaniaInformacjaOUchwale()
    {
        return $this->container['opis_sposobu_powstania_informacja_o_uchwale'];
    }

    /**
     * Sets opis_sposobu_powstania_informacja_o_uchwale
     *
     * @param string|null $opis_sposobu_powstania_informacja_o_uchwale opis_sposobu_powstania_informacja_o_uchwale
     *
     * @return self
     */
    public function setOpisSposobuPowstaniaInformacjaOUchwale($opis_sposobu_powstania_informacja_o_uchwale)
    {
        if (is_null($opis_sposobu_powstania_informacja_o_uchwale)) {
            throw new \InvalidArgumentException('non-nullable opis_sposobu_powstania_informacja_o_uchwale cannot be null');
        }
        $this->container['opis_sposobu_powstania_informacja_o_uchwale'] = $opis_sposobu_powstania_informacja_o_uchwale;

        return $this;
    }

    /**
     * Gets nr_data_decyzji_prezesa_uoki_k
     *
     * @return string|null
     */
    public function getNrDataDecyzjiPrezesaUokiK()
    {
        return $this->container['nr_data_decyzji_prezesa_uoki_k'];
    }

    /**
     * Sets nr_data_decyzji_prezesa_uoki_k
     *
     * @param string|null $nr_data_decyzji_prezesa_uoki_k nr_data_decyzji_prezesa_uoki_k
     *
     * @return self
     */
    public function setNrDataDecyzjiPrezesaUokiK($nr_data_decyzji_prezesa_uoki_k)
    {
        if (is_null($nr_data_decyzji_prezesa_uoki_k)) {
            throw new \InvalidArgumentException('non-nullable nr_data_decyzji_prezesa_uoki_k cannot be null');
        }
        $this->container['nr_data_decyzji_prezesa_uoki_k'] = $nr_data_decyzji_prezesa_uoki_k;

        return $this;
    }

    /**
     * Gets podmioty
     *
     * @return \NIP24\Model\Podmioty[]|null
     */
    public function getPodmioty()
    {
        return $this->container['podmioty'];
    }

    /**
     * Sets podmioty
     *
     * @param \NIP24\Model\Podmioty[]|null $podmioty podmioty
     *
     * @return self
     */
    public function setPodmioty($podmioty)
    {
        if (is_null($podmioty)) {
            throw new \InvalidArgumentException('non-nullable podmioty cannot be null');
        }
        $this->container['podmioty'] = $podmioty;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


