<?php
/**
 * WspolnicySpzoo
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: kontakt@nip24.pl
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * WspolnicySpzoo Class Doc Comment
 *
 * @category Class
 * @package  NIP24
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WspolnicySpzoo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'WspolnicySpzoo';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'nazwisko' => '\NIP24\Model\NazwiskoOsoby',
        'imiona' => '\NIP24\Model\ImionaOsoby',
        'identyfikator' => '\NIP24\Model\IdentyfikatorOsoby',
        'posiadane_udzialy' => 'string',
        'czy_posiada_calosc_udzialow' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'nazwisko' => null,
        'imiona' => null,
        'identyfikator' => null,
        'posiadane_udzialy' => null,
        'czy_posiada_calosc_udzialow' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'nazwisko' => false,
        'imiona' => false,
        'identyfikator' => false,
        'posiadane_udzialy' => false,
        'czy_posiada_calosc_udzialow' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'nazwisko' => 'nazwisko',
        'imiona' => 'imiona',
        'identyfikator' => 'identyfikator',
        'posiadane_udzialy' => 'posiadaneUdzialy',
        'czy_posiada_calosc_udzialow' => 'czyPosiadaCaloscUdzialow'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'nazwisko' => 'setNazwisko',
        'imiona' => 'setImiona',
        'identyfikator' => 'setIdentyfikator',
        'posiadane_udzialy' => 'setPosiadaneUdzialy',
        'czy_posiada_calosc_udzialow' => 'setCzyPosiadaCaloscUdzialow'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'nazwisko' => 'getNazwisko',
        'imiona' => 'getImiona',
        'identyfikator' => 'getIdentyfikator',
        'posiadane_udzialy' => 'getPosiadaneUdzialy',
        'czy_posiada_calosc_udzialow' => 'getCzyPosiadaCaloscUdzialow'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('nazwisko', $data ?? [], null);
        $this->setIfExists('imiona', $data ?? [], null);
        $this->setIfExists('identyfikator', $data ?? [], null);
        $this->setIfExists('posiadane_udzialy', $data ?? [], null);
        $this->setIfExists('czy_posiada_calosc_udzialow', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nazwisko
     *
     * @return \NIP24\Model\NazwiskoOsoby|null
     */
    public function getNazwisko()
    {
        return $this->container['nazwisko'];
    }

    /**
     * Sets nazwisko
     *
     * @param \NIP24\Model\NazwiskoOsoby|null $nazwisko nazwisko
     *
     * @return self
     */
    public function setNazwisko($nazwisko)
    {
        if (is_null($nazwisko)) {
            throw new \InvalidArgumentException('non-nullable nazwisko cannot be null');
        }
        $this->container['nazwisko'] = $nazwisko;

        return $this;
    }

    /**
     * Gets imiona
     *
     * @return \NIP24\Model\ImionaOsoby|null
     */
    public function getImiona()
    {
        return $this->container['imiona'];
    }

    /**
     * Sets imiona
     *
     * @param \NIP24\Model\ImionaOsoby|null $imiona imiona
     *
     * @return self
     */
    public function setImiona($imiona)
    {
        if (is_null($imiona)) {
            throw new \InvalidArgumentException('non-nullable imiona cannot be null');
        }
        $this->container['imiona'] = $imiona;

        return $this;
    }

    /**
     * Gets identyfikator
     *
     * @return \NIP24\Model\IdentyfikatorOsoby|null
     */
    public function getIdentyfikator()
    {
        return $this->container['identyfikator'];
    }

    /**
     * Sets identyfikator
     *
     * @param \NIP24\Model\IdentyfikatorOsoby|null $identyfikator identyfikator
     *
     * @return self
     */
    public function setIdentyfikator($identyfikator)
    {
        if (is_null($identyfikator)) {
            throw new \InvalidArgumentException('non-nullable identyfikator cannot be null');
        }
        $this->container['identyfikator'] = $identyfikator;

        return $this;
    }

    /**
     * Gets posiadane_udzialy
     *
     * @return string|null
     */
    public function getPosiadaneUdzialy()
    {
        return $this->container['posiadane_udzialy'];
    }

    /**
     * Sets posiadane_udzialy
     *
     * @param string|null $posiadane_udzialy posiadane_udzialy
     *
     * @return self
     */
    public function setPosiadaneUdzialy($posiadane_udzialy)
    {
        if (is_null($posiadane_udzialy)) {
            throw new \InvalidArgumentException('non-nullable posiadane_udzialy cannot be null');
        }
        $this->container['posiadane_udzialy'] = $posiadane_udzialy;

        return $this;
    }

    /**
     * Gets czy_posiada_calosc_udzialow
     *
     * @return bool|null
     */
    public function getCzyPosiadaCaloscUdzialow()
    {
        return $this->container['czy_posiada_calosc_udzialow'];
    }

    /**
     * Sets czy_posiada_calosc_udzialow
     *
     * @param bool|null $czy_posiada_calosc_udzialow czy_posiada_calosc_udzialow
     *
     * @return self
     */
    public function setCzyPosiadaCaloscUdzialow($czy_posiada_calosc_udzialow)
    {
        if (is_null($czy_posiada_calosc_udzialow)) {
            throw new \InvalidArgumentException('non-nullable czy_posiada_calosc_udzialow cannot be null');
        }
        $this->container['czy_posiada_calosc_udzialow'] = $czy_posiada_calosc_udzialow;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


