<?php
/**
 * ZaliczkaCzesciowa
 *
 * PHP version 5
 *
 * @category Class
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * NIP24 Service
 *
 * NIP24 Service
 *
 * OpenAPI spec version: 1.3.8
 * Contact: kontakt@nip24.pl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace NIP24\Model;

use \ArrayAccess;
use \NIP24\ObjectSerializer;

/**
 * ZaliczkaCzesciowa Class Doc Comment
 *
 * @category Class
 * @description Dane dla przypadków faktur dokumentujących otrzymanie więcej niż jednej płatności, o której mowa w art. 106b ust. 1 pkt 4 ustawy. W przypadku, gdy faktura, o której mowa w art. 106f ust. 3 ustawy dokumentuje jednocześnie otrzymanie części zapłaty przed dokonaniem czynności, różnica kwoty w polu P_15 i sumy poszczególnych pól P_15Z stanowi kwotę pozostałą ponad płatności otrzymane przed wykonaniem czynności udokumentowanej fakturą
 * @package  NIP24
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ZaliczkaCzesciowa implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ZaliczkaCzesciowa';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'p_6_z' => '\NIP24\Model\TDataT',
'p_15_z' => '\NIP24\Model\TKwotowy',
'kurs_waluty_zw' => '\NIP24\Model\TIlosci'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'p_6_z' => null,
'p_15_z' => null,
'kurs_waluty_zw' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'p_6_z' => 'P_6Z',
'p_15_z' => 'P_15Z',
'kurs_waluty_zw' => 'KursWalutyZW'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'p_6_z' => 'setP6Z',
'p_15_z' => 'setP15Z',
'kurs_waluty_zw' => 'setKursWalutyZw'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'p_6_z' => 'getP6Z',
'p_15_z' => 'getP15Z',
'kurs_waluty_zw' => 'getKursWalutyZw'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['p_6_z'] = isset($data['p_6_z']) ? $data['p_6_z'] : null;
        $this->container['p_15_z'] = isset($data['p_15_z']) ? $data['p_15_z'] : null;
        $this->container['kurs_waluty_zw'] = isset($data['kurs_waluty_zw']) ? $data['kurs_waluty_zw'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['p_6_z'] === null) {
            $invalidProperties[] = "'p_6_z' can't be null";
        }
        if ($this->container['p_15_z'] === null) {
            $invalidProperties[] = "'p_15_z' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets p_6_z
     *
     * @return \NIP24\Model\TDataT
     */
    public function getP6Z()
    {
        return $this->container['p_6_z'];
    }

    /**
     * Sets p_6_z
     *
     * @param \NIP24\Model\TDataT $p_6_z p_6_z
     *
     * @return $this
     */
    public function setP6Z($p_6_z)
    {
        $this->container['p_6_z'] = $p_6_z;

        return $this;
    }

    /**
     * Gets p_15_z
     *
     * @return \NIP24\Model\TKwotowy
     */
    public function getP15Z()
    {
        return $this->container['p_15_z'];
    }

    /**
     * Sets p_15_z
     *
     * @param \NIP24\Model\TKwotowy $p_15_z p_15_z
     *
     * @return $this
     */
    public function setP15Z($p_15_z)
    {
        $this->container['p_15_z'] = $p_15_z;

        return $this;
    }

    /**
     * Gets kurs_waluty_zw
     *
     * @return \NIP24\Model\TIlosci
     */
    public function getKursWalutyZw()
    {
        return $this->container['kurs_waluty_zw'];
    }

    /**
     * Sets kurs_waluty_zw
     *
     * @param \NIP24\Model\TIlosci $kurs_waluty_zw kurs_waluty_zw
     *
     * @return $this
     */
    public function setKursWalutyZw($kurs_waluty_zw)
    {
        $this->container['kurs_waluty_zw'] = $kurs_waluty_zw;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
